name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Checkout Repository
    - name: Checkout code
      uses: actions/checkout@v3

    # 2️⃣ Setup Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # 3️⃣ Install Google Chrome & ChromeDriver (auto-matched)
    - name: Setup Chrome and ChromeDriver
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: stable

    # 4️⃣ Install Python dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r court_data_fetcher/requirements.txt

    # 5️⃣ Run Unit Tests (mock tests recommended for CI)
    - name: Run Pytest
      run: |
        pytest court_data_fetcher/tests/ --maxfail=1 --disable-warnings -q
