name: Python CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v4

    # 2️⃣ Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    # 3️⃣ Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r court_data_fetcher/requirements.txt
        pip install pytest

    # 4️⃣ Run Unit Tests
    - name: Run Unit Tests
      run: |
        cd court_data_fetcher
        pytest tests/ --maxfail=1 --disable-warnings -q
