name: Python CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r court_data_fetcher/requirements.txt
        pip install pytest

    - name: Run Unit Tests
      run: |
        cd court_data_fetcher
        python -m pytest tests/test_app.py --maxfail=1 --disable-warnings -q
